# Only used for testing the docker images
version: '3'
services:
  opensearch-1:
    image: opensearch:test
    environment:
       - node.name=opensearch-1
       - cluster.initial_cluster_manager_nodes=opensearch-1,opensearch-2
       - discovery.seed_hosts=opensearch-2:9300
       - cluster.name=opensearch
       - bootstrap.memory_lock=true
       - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
       - path.repo=/tmp/opensearch-repo
       - node.attr.testattr=test
       - cluster.routing.allocation.disk.watermark.low=1b
       - cluster.routing.allocation.disk.watermark.high=1b
       - cluster.routing.allocation.disk.watermark.flood_stage=1b
       - node.store.allow_mmap=false
    volumes:
       - ./build/repo:/tmp/opensearch-repo
       - ./build/logs/1:/usr/share/opensearch/logs
    ports:
      - "9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  opensearch-2:
    image: opensearch:test
    environment:
       - node.name=opensearch-2
       - cluster.initial_cluster_manager_nodes=opensearch-1,opensearch-2
       - discovery.seed_hosts=opensearch-1:9300
       - cluster.name=opensearch
       - bootstrap.memory_lock=true
       - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
       - path.repo=/tmp/opensearch-repo
       - node.attr.testattr=test
       - cluster.routing.allocation.disk.watermark.low=1b
       - cluster.routing.allocation.disk.watermark.high=1b
       - cluster.routing.allocation.disk.watermark.flood_stage=1b
       - node.store.allow_mmap=false
    volumes:
       - ./build/repo:/tmp/opensearch-repo
       - ./build/logs/2:/usr/share/opensearch/logs
    ports:
      - "9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
