name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Update draft release notes
    runs-on: ubuntu-latest
    steps:
      - name: Update draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: draft-release-notes-config.yml
          name: Version (set here)
          tag: (None)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
