network.host: "0.0.0.0"
node.name: "node-1"
cluster.initial_master_nodes:
- "node-1"
#- "node-2"
#- "node-3"
cluster.name: "khulnasoft-cluster"
#discovery.seed_hosts:
#  - "node-1-ip"
#  - "node-2-ip"
#  - "node-3-ip"
node.max_local_storage_nodes: "3"
path.data: /var/lib/khulnasoft-indexer
path.logs: /var/log/khulnasoft-indexer

plugins.security.ssl.http.pemcert_filepath: /etc/khulnasoft-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/khulnasoft-indexer/certs/indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/khulnasoft-indexer/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: /etc/khulnasoft-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/khulnasoft-indexer/certs/indexer-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/khulnasoft-indexer/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Khulnasoft,O=Khulnasoft,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=node-1,OU=Khulnasoft,O=Khulnasoft,L=California,C=US"
#- "CN=node-2,OU=Khulnasoft,O=Khulnasoft,L=California,C=US"
#- "CN=node-3,OU=Khulnasoft,O=Khulnasoft,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

### Option to allow Filebeat-oss 7.10.2 to work ###
compatibility.override_main_response_version: true