# Only used for testing the docker images
version: '3.7'
services:
  opensearch-1:
    image: opensearch:test
    environment:
       - node.name=opensearch-1
       - cluster.initial_cluster_manager_nodes=opensearch-1
       - cluster.name=opensearch-1
       - bootstrap.memory_lock=true
       - network.publish_host=127.0.0.1
       - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
       - path.repo=/tmp/opensearch-repo
       - node.attr.testattr=test
       - cluster.routing.allocation.disk.watermark.low=1b
       - cluster.routing.allocation.disk.watermark.high=1b
       - cluster.routing.allocation.disk.watermark.flood_stage=1b
       - node.store.allow_mmap=false
    volumes:
       - ./build/repo:/tmp/opensearch-repo
       - ./build/logs/1:/usr/share/opensearch/logs
    ports:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      start_period: 15s
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 2s
      retries: 5
  opensearch-2:
    image: opensearch:test
    environment:
       - node.name=opensearch-2
       - cluster.initial_cluster_manager_nodes=opensearch-2
       - cluster.name=opensearch-2
       - bootstrap.memory_lock=true
       - network.publish_host=127.0.0.1
       - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
       - path.repo=/tmp/opensearch-repo
       - node.attr.testattr=test
       - cluster.routing.allocation.disk.watermark.low=1b
       - cluster.routing.allocation.disk.watermark.high=1b
       - cluster.routing.allocation.disk.watermark.flood_stage=1b
       - node.store.allow_mmap=false
    volumes:
       - ./build/repo:/tmp/opensearch-repo
       - ./build/logs/2:/usr/share/opensearch/logs
    ports:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      start_period: 15s
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 2s
      retries: 5
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: haproxy:2.1.2
    ports:
      - "9600"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - opensearch-2
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9600"]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 15s
