services:
  opensearch-1:
    environment:
      KEYSTORE_PASSWORD: notarealpasswordphrase
      FIPS_GENERATE_TRUSTSTORE: true
      RUN_FIPS_INSTALLER: true
  opensearch-2:
    environment:
      KEYSTORE_PASSWORD: notarealpasswordphrase
      FIPS_GENERATE_TRUSTSTORE: true
      RUN_FIPS_INSTALLER: true
