# Only used for testing the docker images
version: '3.7'
services:
  opensearch-default-1:
    image: opensearch:test
    environment:
       - node.name=opensearch-default-1
       - cluster.initial_master_nodes=opensearch-default-1
       - cluster.name=opensearch-default-1
       - bootstrap.memory_lock=true
       - network.publish_host=127.0.0.1
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       - path.repo=/tmp/opensearch-repo
       - node.attr.testattr=test
       - cluster.routing.allocation.disk.watermark.low=1b
       - cluster.routing.allocation.disk.watermark.high=1b
       - cluster.routing.allocation.disk.watermark.flood_stage=1b
       - node.store.allow_mmap=false
    volumes:
       - ./build/repo:/tmp/opensearch-repo
       - ./build/certs/testnode.jks:/usr/share/opensearch/config/testnode.jks
       - ./build/logs/default-1:/usr/share/opensearch/logs
       - ./docker-test-entrypoint.sh:/docker-test-entrypoint.sh
    ports:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    entrypoint: /docker-test-entrypoint.sh
    healthcheck:
      start_period: 15s
      test: ["CMD", "curl", "-f", "-u", "rest_user:test-password", "-k", "https://localhost:9200"]
      interval: 10s
      timeout: 2s
      retries: 5
  opensearch-default-2:
    image: opensearch:test
    environment:
       - node.name=opensearch-default-2
       - cluster.initial_master_nodes=opensearch-default-2
       - cluster.name=opensearch-default-2
       - bootstrap.memory_lock=true
       - network.publish_host=127.0.0.1
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       - path.repo=/tmp/opensearch-repo
       - node.attr.testattr=test
       - cluster.routing.allocation.disk.watermark.low=1b
       - cluster.routing.allocation.disk.watermark.high=1b
       - cluster.routing.allocation.disk.watermark.flood_stage=1b
       - node.store.allow_mmap=false
    volumes:
       - ./build/repo:/tmp/opensearch-repo
       - ./build/certs/testnode.jks:/usr/share/opensearch/config/testnode.jks
       - ./build/logs/default-2:/usr/share/opensearch/logs
       - ./docker-test-entrypoint.sh:/docker-test-entrypoint.sh
    ports:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    entrypoint: /docker-test-entrypoint.sh
    healthcheck:
      start_period: 15s
      test: ["CMD", "curl", "-f", "-u", "rest_user:test-password", "-k", "https://localhost:9200"]
      interval: 10s
      timeout: 2s
      retries: 5
  haproxy:
    image: haproxy:2.1.2
    ports:
      - "9600"
    volumes:
      - ./haproxy-default.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
