name: Apply all issue labels to PR

on:
  pull_request:
  pull_request_target:

jobs:
  copy-labels:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ubuntu-latest
    name: Copy labels from linked issues
    steps:
      - name: copy-labels
        uses: DarshitChanpura/copy-issue-labels@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-to-exclude: |
            untriaged
            triaged

