name: Gradle Check
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/14.0.2-12/x64/
      JAVA11_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/
      JAVA8_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.292-1/x64/
      JAVA14_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/14.0.2-12/x64/
      JAVA17_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.1-12/x64/
    steps:
      - name: Checkout OpenSearch 
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          targets: 'JDK_8'
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          targets: 'JDK_11'
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          targets: 'JDK_17'
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '14'
          targets: 'JDK_14'
      - uses: actions/checkout@v2
      - name: Run Gradle
        run: ./gradlew check --parallel
