name: Code Hygiene

on: [pull_request]

jobs:
  linelint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-22.04', 'ubuntu-20.04', 'ubuntu-latest' ]
    name: Check if all files end in newline
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Linelint
        uses: fernandrone/linelint@0.0.4
