name: Identity Tests
on: [pull_request]

jobs:
  identity-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Run Identity internalClusterTest
        run: |
          ./gradlew :sandbox:modules:identity:internalClusterTest

      - name: Run Identity test
        run: |
          ./gradlew :sandbox:modules:identity:test
