name: Publish to Maven Local

on:
  pull_request:
    branches: [ feature/datafusion ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-A unused_variables -A unused_mut"

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install Protocol Buffers
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Publish to Maven Local
      run: ./gradlew publishToMavenLocal
