name: Pull Request Checks

on:
  pull_request:
    types:
      [
        opened,
        edited,
        review_requested,
        synchronize,
        reopened,
        ready_for_review,
      ]

jobs:
  verify-description-checklist:
    name: Verify Description Checklist
    runs-on: ubuntu-latest
    steps:
      - uses: peternied/check-pull-request-description-checklist@v1.1
        if: github.actor != 'dependabot[bot]'
        with:
          checklist-items: |
            New functionality includes testing.
            All tests pass
            New functionality has been documented.
            New functionality has javadoc added
            Commits are signed per the DCO using --signoff
            Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
