name: Increment Version

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'the tag'
        required: true
        type: string
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write
  issues: write
jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Tag and Version Information
        run: |
          TAG=${{ github.event.inputs.tag }}
          CURRENT_VERSION_ARRAY=($(echo "$TAG" | tr . '\n'))
          BASE=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:2}")
          BASE_X=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:1}.x")
          CURRENT_VERSION=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:3}")
          CURRENT_VERSION_ARRAY[2]=$((CURRENT_VERSION_ARRAY[2]+1))
          NEXT_VERSION=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:3}")
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "BASE=$BASE" >> $GITHUB_ENV
          echo "BASE_X=$BASE_X" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - id: create-issue
        uses: actions/github-script@v6.4.0
        with:
          script: |
            const { data: issue }= await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Increment version for ${{ env.NEXT_VERSION }}",
              body: "Issue for tracking the changes associated with a version increment."
            });
            console.error(JSON.stringify(issue));
            return issue.number;
          result-encoding: string
            
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE }}

      - name: Increment Patch Version on Major.Minor branch
        uses: peternied/opensearch-core-version-updater@main
        with:
          previous-version: ${{ env.CURRENT_VERSION }}
          new-version: ${{ env.NEXT_VERSION }}
          update-current: true

      - run: git diff
      - run: |
          git config --global user.name 'Peter Nied'
          git config --global user.email 'petern@amazon.com'
          git add .
          git commit -s -m "Increment version to $NEXT_VERSION #${{steps.create-issue.outputs.result}}"
          git push

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_X }}

      - name: Add Patch Version on Major.X branch
        uses: peternied/opensearch-core-version-updater@main
        with:
          previous-version: ${{ env.CURRENT_VERSION }}
          new-version: ${{ env.NEXT_VERSION }}
          update-current: false

      - run: git diff
      - run: |
          git config --global user.name 'Peter Nied'
          git config --global user.email 'petern@amazon.com'
          git add .
          git commit -s -m "Add patch version $NEXT_VERSION #${{steps.create-issue.outputs.result}}"
          git push

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Add Patch Version on Main branch
        uses: peternied/opensearch-core-version-updater@main
        with:
          previous-version: ${{ env.CURRENT_VERSION }}
          new-version: ${{ env.NEXT_VERSION }}
          update-current: false

      - run: git diff
      - run: |
          git config --global user.name 'Peter Nied'
          git config --global user.email 'petern@amazon.com'
          git add .
          git commit -s -m "Add patch version $NEXT_VERSION #${{steps.create-issue.outputs.result}}"
          git push

      - uses: actions/github-script@v6.4.0
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: "${{steps.create-issue.outputs.result}}",
              state: "closed"
            });